### ISSUE TITLE
Where to find current background file ?

### ISSUE THREAD

**Issue by pseudomyne** [derf/feh#422]
Hi, 
Thank you for `feh`. I like to use `feh` as a random bg displayer. Is there a way to locate current bg file ? 
Arch linux here. 
Thanks.

**Comment by derf** [comment]
The current background file (and a commandline for restoring it) is saved in `~/.fehbg`, as [documented in the manual](https://man.finalrewind.org/1/feh/#x4241434b47524f554e44x20x53455454494e47)

**Comment by pseudomyne** [comment]
Thanks for your answer. My `~/.fehbg` file only contains 
```
#!/bin/sh
feh --bg-fill 
```
No indication of current background file

**Comment by derf** [comment]
Which version of feh are you using? How are you setting your background?

**Comment by pseudomyne** [comment]
Hi, 
feh version 2.27.1
I set my background with `feh --randomize --bg-fill ~/Images/`

**Comment by derf** [comment]
Oh. Yes, that's a bug I can reproduce. Thanks for reporting!

**Comment by derf** [comment]
Fixed in 3.1.2, I forgot to tag this issue in the commit.

**Comment by pseudomyne** [comment]
Thank you. It works : the first file in `~/.fehbg` indeed is the random file feh has just picked and so I can see what file it is. That's fine !

**Comment by 38569459** [comment]
I'm in feh version 3.5 but still have this bug.

- feh --version:
```
feh version 3.5
Compile-time switches: curl exif inotify help stat64 verscmp xinerama
```

- cat .fehbg

```
#!/bin/sh
feh --no-fehbg --bg-fill [path here]
```

I'm setting my background by using shortcut in i3wm.
